# Generated by Django 3.2.5 on 2021-07-24 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='start_date',
        ),
    ]
